# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: yeluyang.awesome
author: yeluyang
email: ylycpg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  一个后端程序员的博客, 记录和分享计算机技术
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: yeluyang

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - LICENSE.txt
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

timezone: Asia/Shanghai

defaults:
  - scope:
      path: ""
    values:
      layout: article
      toc: true
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:title
  - scope:
      path: ""
      type: drafts
    values:
      permalink: /:categories/:title

collections_dir: docs
collections:
  git:
    output: true
    order:
      - "index.md"
  vim:
    output: true
    order:
      - "index.md"
  tmux:
    output: true
    order:
      - "index.md"
  algorithm:
    output: true
    order:
      - "index.md"
  rust:
    output: true
    order:
      - "index.md"
  golang:
    output: true
    order:
      - "index.md"
  python:
    output: true
    order:
      - "index.md"
